SECRET_KEY = 'wa58RZIb4mCf'
CLIENT_ID = 'RHqQ3tjgkwOJKw'
CLIENT_SECRET = 'Wn3mJAnqgc8ib44XlPjZuTzcywY'
#REDIRECT_URI = 'http://127.0.0.1:65010/authorize_callback'
REDIRECT_URI = 'http://nba-gamethread-generator.herokuapp.com/authorize_callback'
REDDIT_AUTH_URL = ''
